version: '3.0'
services:
  app:
    build:
      context: .
      args:
        RUBY_VERSION: 2.4.2
    volumes:
      - vendor:/vendor
      - home:/home/ruby
      - .:/app:cached
volumes:
  home:
  vendor:
